### ISSUE TITLE
Adding additional domains? (e.g. Do you just edit getDoms()?)

### ISSUE THREAD

**Issue by victorhooi** [samyk/poisontap#110]
Is there a procedure for adding additional domains to the list of domains to backdoor?

I see there's a shell script `alexa1m.sh`:

https://github.com/samyk/poisontap/blob/8263c64c62fcc335e2df3f650dcbe490459d1e71/alexa1m.sh

However, is this script actually called from anywhere? I can't seem to find any mentions of it being called in the repo.

Also, in `target_injected_xhtmljs.html` there's a `getDoms()` function:

https://github.com/samyk/poisontap/blob/8263c64c62fcc335e2df3f650dcbe490459d1e71/target_injected_xhtmljs.html#L2578

Is it possible to simple append a domain to this function? Or do you also need to amend elsewhere?

**Comment by samyk** [comment]
Just amend that one function. The alexa1m.sh is just shared to allow people to easily grab the list.

**Comment by victorhooi** [comment]
Awesome, thanks for quick reply!

Was finally going to get some time to play with the code this weekend.

Do you think it's worth documenting these sorts of questions (e.g. how to add domains, how to remove etc.) in a FAQ or wiki somewhere? (There doesn't seem to be a Github wiki for it yet). Or perhaps just append it to the README.md somewhere? Let me know if you have a preferred location and I'm happy to file a PR.

**Comment by samyk** [comment]
Sweet. I think amending the README, perhaps with a FAQ, would be awesome!

**Comment by victorhooi** [comment]
Done - https://github.com/samyk/poisontap/pull/111
