### ISSUE TITLE
error when i run pi_startup.sh ls: failed

### ISSUE THREAD

**Issue by theCake75** [samyk/poisontap#118]
error when i run pi_startup.sh
```
ln: failed to create symbolic link ‘configs/c.1/acm.usb0’: File exists
sh: echo: I/O error
sh: echo: I/O error
ln: failed to create symbolic link ‘configs/c.1/ecm.usb0’: File exists
ls: write error: Device or resource busy
ifup: interface usb0 already configured
SIOCADDRT: File exists
```
didnt modify the file
EDIT : 
I solved my problem thx

**Comment by samyk** [comment]
I believe these errors are okay as PoisonTap just reattempts to setup the USB network interface each time it starts up.

**Comment by theCake75** [comment]
@samyk 
![pi](https://user-images.githubusercontent.com/29002810/27015056-a0ed3252-4f05-11e7-882d-2544bc842bdd.jpg)

when I plug hdmi cable on pi zero i see that, and it don't move
freez on "errypi login:
net.ipv4.ip_forward = 1
"
no network detected on the target pc (windows 10)

thank for your reply !


EDIT : 
![19114822_10155208726952420_934286904_n](https://user-images.githubusercontent.com/29002810/27015190-8e6142ba-4f08-11e7-891a-8dd72a9cc31b.jpg)

Sometimes it work like that when I try again, i tried after change idproduct and idvendor as you specified on pi_startup.sh but nothing happened, no detected device in device manager
