### ISSUE TITLE
Raspberry Pi 3 can only work with Ethernet-to-USB/Thunderbolt dongle? 

### ISSUE THREAD

**Issue by iblh** [samyk/poisontap#23]
Raspberry zero can connect with a micro-USB cable, looks much portable.
Is there any reason why RP3 could not use the micro-USB cable?

**Comment by JonathanNathanson** [comment]
Worth looking through the other questions before you post:

https://github.com/samyk/poisontap/issues/6

Other than what's mentioned in there, I've tried running RP3 via USB for various practical reasons and find that the RP3 is pretty sensitive to fluctuations in power (which are common when powering from a PC / laptop USB port etc). It's a far more power-hungry device than the PiZero.

If you are using a proper power supply then it's just the challenges in the above issue you'd need to work around, which sounds like it may be complicated.
