### ISSUE TITLE
Can't get started 

### ISSUE THREAD

**Issue by wildchicken88** [samyk/poisontap#25]
Hi. I try run poison tap on my RPiZero. But still this same problem. 

Any solution ? 
When I use `sudo ./pi_startup.sh` I got error 

> ls: write error: Device or resource busy
Ignoring unknown interface usb0=usb0.
./pi_startup.sh: 42: ./pi_startup.sh: /etc/init.d/isc-dhcp-server: not found
net.ipv4.ip_forward = 1

But if I use  `./pi_startup.sh`
 

> ./pi_startup.sh: 11: ./pi_startup.sh: cannot create idVendor: Permission denied
./pi_startup.sh: 12: ./pi_startup.sh: cannot create idProduct: Permission denied
./pi_startup.sh: 13: ./pi_startup.sh: cannot create bcdDevice: Permission denied
./pi_startup.sh: 14: ./pi_startup.sh: cannot create bcdUSB: Permission denied
./pi_startup.sh: 16: ./pi_startup.sh: cannot create strings/0x409/serialnumber: Permission denied
./pi_startup.sh: 17: ./pi_startup.sh: cannot create strings/0x409/manufacturer: Permission denied
./pi_startup.sh: 18: ./pi_startup.sh: cannot create strings/0x409/product: Permission denied
./pi_startup.sh: 20: ./pi_startup.sh: cannot create configs/c.1/strings/0x409/configuration: Permission denied
./pi_startup.sh: 21: ./pi_startup.sh: cannot create configs/c.1/MaxPower: Permission denied
ln: failed to create symbolic link ‘configs/c.1/acm.usb0’: File exists
./pi_startup.sh: 33: ./pi_startup.sh: cannot create functions/ecm.usb0/host_addr: Permission denied
./pi_startup.sh: 34: ./pi_startup.sh: cannot create functions/ecm.usb0/dev_addr: Permission denied
ln: failed to create symbolic link ‘configs/c.1/ecm.usb0’: File exists
./pi_startup.sh: 36: ./pi_startup.sh: cannot create UDC: Permission denied
ifup: failed to open lockfile /run/network/.ifstate.lock: Permission denied
SIOCSIFFLAGS: Operation not permitted
SIOCADDRT: Operation not permitted
./pi_startup.sh: 42: ./pi_startup.sh: /etc/init.d/isc-dhcp-server: not found
sysctl: permission denied on key 'net.ipv4.ip_forward'
iptables v1.4.21: can't initialize iptables table `nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

**Comment by samyk** [comment]
Follow the Installation portion of the README
