### ISSUE TITLE
Installation Smooth & Great But... Not Working...

### ISSUE THREAD

**Issue by bibi1959** [samyk/poisontap#41]
I run through the installation following all (i hope) aspects including the config.txt and cmdline.xt By booting up and connecting to my Mac - the eth card is there but any site/browser and program using inet connection just doesn't open.  As soon as i disconnect everything is back to normal. Sorry for the silly question... but does anybody knows what i did wrong? Please get back if you need more info. Bruno
![1](https://cloud.githubusercontent.com/assets/16669244/20574118/f5deca26-b1aa-11e6-8594-71a4ca6954dc.png)
![i2](https://cloud.githubusercontent.com/assets/16669244/20574123/fb81f07a-b1aa-11e6-97c5-0614d2443950.png)

**Comment by belialboy** [comment]
Did you ever fix this. My PiZ seems to be in a similar state as yours. I'm seeing the same "PoisonTap is listening" lines in the log, but when it's plugged into my Win10 machine, I see tumbleweeds. Nothing. Nada.

**Comment by Leyart** [comment]
Be sure that your /etc/rc.local was empty before trying to start PoisonTap. With a traditional rasp installation, the /et/rc.local has an exit 0 before the line that we have appended

**Comment by belialboy** [comment]
Yep, I saw that and fixed it... actually I worked out the noob mistake I'd made. With the jumble of wires on my desktop I'd inadvertently plugged by PC into the PWR USB slot rather than the USB labelled one on the PiZero. Well that's 6 hours I won't get back!
