### ISSUE TITLE
Retrieve cookies from Pi after attack

### ISSUE THREAD

**Issue by bakerkretzmar** [samyk/poisontap#93]
Now that everything is set up, how will I ssh back into the Pi later without running the attack on myself? If I plug it in to my laptop is there any way to stop the attack from beginning automatically, so that I can go in and get the existing cookies? Or can I get them from the SD card alone?

Thanks!

**Comment by samyk** [comment]
Close your browser, then power up pi and you can safely ssh into 1.0.0.1.
