### ISSUE TITLE
Cookies 

### ISSUE THREAD

**Issue by chuspepe79** [samyk/poisontap#96]
Hello,
Posiontap is wonderful! It works properly and captures many cookies.
I would like to know how I can inject captured cookies into my browser for testing. I have tried to do it with Greasemonkey in Firefox and with Editthiscookie in Chrome and I do not get it. I do not understand the cookie structure captured by the PoisonTap.
Greetings.

**Comment by samyk** [comment]
You can use document.cookies in the console to set a cookie (while on the domain you want to inject them into). https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie
